// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table PERMUTATIONS {
  id int [pk]
  primary_dashboard_name varchar
  secondary_dashboard_name varchar
  configapp_dashboard_name varchar
  block_xbox_live boolean
  stealth_server_name varchar
  alpha_plugin_name varchar
  beta_plugin_name varchar
  gamma_plugin_name varchar
  delta_plugin_name varchar
}

Table DASHBOARDS {
  name varchar [pk]
  mount_path varchar
  folder_path varchar
  folder_name varchar
  executable varchar
}

Table DASHBOARD_VERSIONS {
  name varchar [pk]
  official boolean
  legacy boolean
  minimum_version int
}

Table COMMON_EXECUTABLES {
  name varchar [pk]
}

Table MOUNT_PATHS {
  label varchar [pk]
  name varchar [not null]
}

Table PLUGINS {
  name varchar [pk]
  type varchar
  mount_path varchar
  folder_path varchar
  folder_name varchar
  executable varchar
}

Table PLUGIN_COMMON_PATHS {
  type varchar [pk]
  name varchar
}

Table PLUGIN_RANKS {
  index integer [pk]
  type varchar [not null]
  maximum_count integer
}

Table PLUGIN_STEALTH_SERVERS {
  name varchar [pk]
  supports_backwards_compatibility boolean
  supports_cheats boolean
  has_custom_hud boolean
  supports_custom_hud boolean
  is_freeware boolean
  is_paidware boolean
  is_shareware boolean
  supports_stealth_network boolean
}

Ref: "PERMUTATIONS"."primary_dashboard_name" > "DASHBOARDS"."name"
Ref: "PERMUTATIONS"."secondary_dashboard_name" > "DASHBOARDS"."name"
Ref: "PERMUTATIONS"."configapp_dashboard_name" > "DASHBOARDS"."name"
Ref: "PERMUTATIONS"."stealth_server_name" > "PLUGIN_STEALTH_SERVERS"."name"
Ref: "PERMUTATIONS"."alpha_plugin_name" > "PLUGINS"."name"
Ref: "PERMUTATIONS"."beta_plugin_name" > "PLUGINS"."name"
Ref: "PERMUTATIONS"."gamma_plugin_name" > "PLUGINS"."name"
Ref: "PERMUTATIONS"."delta_plugin_name" > "PLUGINS"."name"

Ref: "DASHBOARDS"."name" > "DASHBOARD_VERSIONS"."name"
Ref: "DASHBOARDS"."mount_path" < "MOUNT_PATHS"."label"
Ref: "PLUGIN_STEALTH_SERVERS"."name" > "PLUGINS"."name"

Ref: "PLUGINS"."mount_path" < "MOUNT_PATHS"."label"
Ref: "PLUGINS"."type" > "PLUGIN_COMMON_PATHS"."type"
Ref: "PLUGINS"."type" < "PLUGIN_RANKS"."type"