// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table PERMUTATIONS {
  id integer [pk]
  first_dashboard_id integer
  second_dashboard_id integer
  configapp_dashboard_id integer
  block_xbox_live boolean
  first_plugin_id integer
  second_plugin_id integer
  third_plugin_id integer
  fourth_plugin_id integer
  fifth_plugin_id integer
}

Table DASHBOARDS {
  id integer [pk]
  mount_path_id integer
  root_folder_path_id integer
  executable varchar
  name varchar
  this_folder_name varchar
}

Table DASHBOARD_ROOT_PATHS {
  id integer [pk]
  name varchar
}

Table DASHBOARD_VERSIONS {
  id integer [pk]
  dashboard_id integer
  name varchar
  official boolean
  legacy boolean
  minimum_version int
}

Table COMMON_EXECUTABLES {
  id integer [pk]
  name varchar
}

Table MOUNT_PATHS {
  id integer [pk]
  path varchar
  name varchar
}

Table PLUGINS {
  id integer [pk]
  mount_path_id integer
  root_folder_path_id integer
  type_id integer
  executable varchar
  name varchar
  this_folder_name varchar
}

Table PLUGIN_ROOT_PATHS {
  id integer [pk]
  is_valid boolean
  name varchar
  path varchar
}

Table PLUGIN_TYPES {
  id integer [pk]
  path varchar
  type varchar
}

Table PLUGIN_RANKS {
  id integer [pk]         // Valid: 0-4
  type_id integer
  maximum_count integer   // Min: 1; Max: 5
}

Table PLUGIN_STEALTH_SERVERS {
  id integer [pk]
  plugin_id integer
  name varchar
  this_folder_name varchar
  supports_backwards_compatibility boolean
  supports_cheats boolean
  has_custom_hud boolean
  supports_custom_hud boolean
  is_freeware boolean
  is_paidware boolean
  is_shareware boolean
  is_online_only boolean
  supports_stealth_network boolean
}

Ref: "PERMUTATIONS"."first_dashboard_id" < "DASHBOARDS"."id"
Ref: "PERMUTATIONS"."second_dashboard_id" < "DASHBOARDS"."id"
Ref: "PERMUTATIONS"."configapp_dashboard_id" < "DASHBOARDS"."id"
Ref: "PERMUTATIONS"."first_plugin_id" < "PLUGINS"."id"
Ref: "PERMUTATIONS"."second_plugin_id" < "PLUGINS"."id"
Ref: "PERMUTATIONS"."third_plugin_id" < "PLUGINS"."id"
Ref: "PERMUTATIONS"."fourth_plugin_id" < "PLUGINS"."id"
Ref: "PERMUTATIONS"."fifth_plugin_id" < "PLUGINS"."id"

Ref: "DASHBOARDS"."id" < "DASHBOARD_VERSIONS"."dashboard_id"
Ref: "DASHBOARDS"."root_folder_path_id" < "DASHBOARD_ROOT_PATHS"."id"
Ref: "DASHBOARDS"."mount_path_id" < "MOUNT_PATHS"."id"

Ref: "PLUGINS"."id" < "PLUGIN_STEALTH_SERVERS"."plugin_id"
Ref: "PLUGINS"."type_id" < "PLUGIN_TYPES"."id"
Ref: "PLUGINS"."mount_path_id" < "MOUNT_PATHS"."id"
Ref: "PLUGINS"."root_folder_path_id" < "PLUGIN_ROOT_PATHS"."id"

Ref: "PLUGIN_TYPES"."id" < "PLUGIN_RANKS"."type_id"