// USE DBML TO DEFINE YOUR DATABASE STRUCTURE
// DOCS: HTTPS://DBML.DBDIAGRAM.IO/DOCS

TABLE COMMON_EXECUTABLES {
  ID INTEGER [PK]
  NAME VARCHAR
}

TABLE DASHBOARDS {
  ID INTEGER [PK]
  MOUNT_PATH_ID INTEGER
  ROOT_FOLDER_PATH_ID INTEGER
  EXECUTABLE VARCHAR
  NAME VARCHAR
  THIS_FOLDER_NAME VARCHAR
}

TABLE DASHBOARD_OFFICIAL_PATHS {
  ID INTEGER [PK]
  IS_VALID BOOLEAN
  PATH VARCHAR
}

TABLE DASHBOARD_ROOT_PATHS {
  ID INTEGER [PK]
  IS_VALID BOOLEAN
  NAME VARCHAR
}

TABLE DASHBOARD_VERSIONS {
  ID INTEGER [PK]
  DASHBOARD_ID INTEGER
  NAME VARCHAR
  OFFICIAL BOOLEAN
  LEGACY BOOLEAN
  MINIMUM_VERSION INT
}

TABLE MOUNT_PATHS {
  ID INTEGER [PK]
  PATH VARCHAR
  NAME VARCHAR
}

TABLE PERMUTATIONS {
  ID INTEGER [PK]
  FIRST_DASHBOARD_ID INTEGER
  SECOND_DASHBOARD_ID INTEGER
  CONFIGAPP_DASHBOARD_ID INTEGER
  BLOCK_XBOX_LIVE BOOLEAN
  FIRST_PLUGIN_ID INTEGER
  SECOND_PLUGIN_ID INTEGER
  THIRD_PLUGIN_ID INTEGER
  FOURTH_PLUGIN_ID INTEGER
  FIFTH_PLUGIN_ID INTEGER
  IS_VALID BOOLEAN
  NOTES VARCHAR
}

TABLE PLUGINS {
  ID INTEGER [PK]
  MOUNT_PATH_ID INTEGER
  ROOT_FOLDER_PATH_ID INTEGER
  TYPE_ID INTEGER
  EXECUTABLE VARCHAR
  NAME VARCHAR
  THIS_FOLDER_NAME VARCHAR
}

TABLE PLUGIN_RANKS {
  ID INTEGER [PK]         // MIN: 0; MAX: 4
  TYPE_ID INTEGER
  MAXIMUM_COUNT INTEGER   // MIN: 1; MAX: 5
}

TABLE PLUGIN_ROOT_PATHS {
  ID INTEGER [PK]
  IS_VALID BOOLEAN
  NAME VARCHAR
}

TABLE PLUGIN_STEALTH_SERVERS {
  ID INTEGER [PK]
  PLUGIN_ID INTEGER
  SUPPORTS_BACKWARDS_COMPATIBILITY BOOLEAN
  SUPPORTS_CHEATS BOOLEAN
  HAS_CUSTOM_HUD BOOLEAN
  SUPPORTS_CUSTOM_HUD BOOLEAN
  IS_FREEWARE BOOLEAN
  IS_PAIDWARE BOOLEAN
  IS_SHAREWARE BOOLEAN
  IS_ONLINE_ONLY BOOLEAN
  SUPPORTS_STEALTH_NETWORK BOOLEAN
}

TABLE PLUGIN_TYPES {
  ID INTEGER [PK]
  PATH_ID INTEGER
  TYPE VARCHAR
}

TABLE PLUGIN_TYPE_PATHS {
  ID INTEGER [PK]
  TYPE_ID INTEGER
  IS_VALID BOOLEAN
  PATH VARCHAR
}

REF: "PERMUTATIONS"."FIRST_DASHBOARD_ID" < "DASHBOARDS"."ID"
REF: "PERMUTATIONS"."SECOND_DASHBOARD_ID" < "DASHBOARDS"."ID"
REF: "PERMUTATIONS"."CONFIGAPP_DASHBOARD_ID" < "DASHBOARDS"."ID"
REF: "PERMUTATIONS"."FIRST_PLUGIN_ID" < "PLUGINS"."ID"
REF: "PERMUTATIONS"."SECOND_PLUGIN_ID" < "PLUGINS"."ID"
REF: "PERMUTATIONS"."THIRD_PLUGIN_ID" < "PLUGINS"."ID"
REF: "PERMUTATIONS"."FOURTH_PLUGIN_ID" < "PLUGINS"."ID"
REF: "PERMUTATIONS"."FIFTH_PLUGIN_ID" < "PLUGINS"."ID"

REF: "DASHBOARDS"."ID" < "DASHBOARD_VERSIONS"."DASHBOARD_ID"
REF: "DASHBOARDS"."ROOT_FOLDER_PATH_ID" < "DASHBOARD_ROOT_PATHS"."ID"
REF: "DASHBOARDS"."MOUNT_PATH_ID" < "MOUNT_PATHS"."ID"

REF: "PLUGINS"."ID" < "PLUGIN_STEALTH_SERVERS"."PLUGIN_ID"
REF: "PLUGINS"."TYPE_ID" < "PLUGIN_TYPES"."ID"
REF: "PLUGINS"."MOUNT_PATH_ID" < "MOUNT_PATHS"."ID"
REF: "PLUGINS"."ROOT_FOLDER_PATH_ID" < "PLUGIN_ROOT_PATHS"."ID"

REF: "PLUGIN_TYPES"."ID" < "PLUGIN_RANKS"."TYPE_ID"
REF: "PLUGIN_TYPES"."PATH_ID" < "PLUGIN_TYPE_PATHS"."ID"