CREATE TABLE "DASHBOARD_VERSIONS" (
	"ID"	INTEGER,
	"DASHBOARD_ID"	INTEGER,
	"NAME"	TEXT NOT NULL,
	"OFFICIAL"	INTEGER NOT NULL CHECK("OFFICIAL" IN (0, 1)),
	"LEGACY"	INTEGER NOT NULL CHECK("LEGACY" IN (0, 1)),
	"MINIMUM_VERSION"	INTEGER CHECK("MINIMUM_VERSION" >= 0),
	PRIMARY KEY("ID") ON CONFLICT ROLLBACK,
	FOREIGN KEY("DASHBOARD_ID") REFERENCES "DASHBOARDS"("ID")
) STRICT