CREATE TABLE "PLUGINS" (
	"ID"	INTEGER,
	"MOUNT_PATH_ID"	INTEGER,
	"ROOT_FOLDER_PATH_ID"	INTEGER,
	"TYPE_ID"	INTEGER,
	"EXECUTABLE"	TEXT NOT NULL,
	"NAME"	TEXT NOT NULL,
	"THIS_FOLDER_NAME"	TEXT NOT NULL,
	PRIMARY KEY("ID") ON CONFLICT ROLLBACK,
	FOREIGN KEY("MOUNT_PATH_ID") REFERENCES "MOUNT_PATHS"("ID"),
	FOREIGN KEY("ROOT_FOLDER_PATH_ID") REFERENCES "PLUGIN_ROOT_PATHS"("ID"),
	FOREIGN KEY("TYPE_ID") REFERENCES "PLUGIN_TYPES"("ID")
) STRICT