CREATE TABLE "PLUGIN_STEALTH_SERVERS" (
	"ID"	INTEGER,
	"PLUGIN_ID"	INTEGER,
	"SUPPORTS_BACKWARDS_COMPATIBILITY"	INTEGER NOT NULL CHECK("SUPPORTS_BACKWARDS_COMPATIBILITY" IN (0, 1)),
	"SUPPORTS_CHEATS"	INTEGER NOT NULL CHECK("SUPPORTS_CHEATS" IN (0, 1)),
	"HAS_CUSTOM_HUD"	INTEGER NOT NULL CHECK("HAS_CUSTOM_HUD" IN (0, 1)),
	"SUPPORTS_CUSTOM_HUD"	INTEGER NOT NULL CHECK("SUPPORTS_CUSTOM_HUD" IN (0, 1)),
	"IS_FREEWARE"	INTEGER NOT NULL CHECK("IS_FREEWARE" IN (0, 1)),
	"IS_PAIDWARE"	INTEGER NOT NULL CHECK("IS_PAIDWARE" IN (0, 1)),
	"IS_SHAREWARE"	INTEGER NOT NULL CHECK("IS_SHAREWARE" IN (0, 1)),
	"IS_ONLINE_ONLY"	INTEGER NOT NULL CHECK("IS_ONLINE_ONLY" IN (0, 1)),
	"SUPPORTS_STEALTH_NETWORK"	INTEGER NOT NULL CHECK("SUPPORTS_STEALTH_NETWORK" IN (0, 1)),
	PRIMARY KEY("ID") ON CONFLICT ROLLBACK,
	FOREIGN KEY("PLUGIN_ID") REFERENCES "PLUGINS"("ID")
) STRICT