CREATE TABLE "PLUGIN_RANKS" (
	"ID"	INTEGER CHECK("ID" BETWEEN 0 AND 4),
	"TYPE_ID"	INTEGER,
	"MAXIMUM_COUNT"	INTEGER NOT NULL CHECK("MAXIMUM_COUNT" BETWEEN 1 AND 5),
	PRIMARY KEY("ID") ON CONFLICT ROLLBACK,
	FOREIGN KEY("TYPE_ID") REFERENCES "PLUGIN_TYPES"("ID")
) STRICT