CREATE TRIGGER VALIDATE_PERMUTATION_PLUGINS
BEFORE INSERT ON PERMUTATIONS
FOR EACH ROW
WHEN (
  SELECT COUNT(*) FROM (
    SELECT NEW.FIRST_PLUGIN_ID AS PID WHERE PID IS NOT NULL
    UNION ALL SELECT NEW.SECOND_PLUGIN_ID WHERE NEW.SECOND_PLUGIN_ID IS NOT NULL
    UNION ALL SELECT NEW.THIRD_PLUGIN_ID WHERE NEW.THIRD_PLUGIN_ID IS NOT NULL
    UNION ALL SELECT NEW.FOURTH_PLUGIN_ID WHERE NEW.FOURTH_PLUGIN_ID IS NOT NULL
    UNION ALL SELECT NEW.FIFTH_PLUGIN_ID WHERE NEW.FIFTH_PLUGIN_ID IS NOT NULL
  ) GROUP BY PID HAVING COUNT(*) > 1
) IS NOT NULL
BEGIN
  SELECT RAISE(ABORT, 'Duplicate plugins detected in permutation slots');
END;