CREATE TRIGGER VALIDATE_PLUGIN_TYPE_STEALTH_SERVER
BEFORE INSERT ON PLUGIN_STEALTH_SERVERS
FOR EACH ROW
BEGIN
  SELECT CASE
    WHEN (
      SELECT T.TYPE FROM PLUGINS P 
      JOIN PLUGIN_TYPES T ON P.TYPE_ID = T.ID 
      WHERE P.ID = NEW.PLUGIN_ID
    ) != 'Stealth'
    THEN RAISE(ABORT, 'Referenced plugin must be a Stealth Server.')
  END;
END